site_name: GlinrDock Documentation
site_description: Lightweight, secure container management platform
site_author: GLINCKER LLC
site_url: https://glincker.github.io/glinrdock-release/

repo_name: GLINCKER/glinrdock-release
repo_url: https://github.com/GLINCKER/glinrdock-release
edit_uri: edit/main/docs/

docs_dir: docs
site_dir: site

theme:
  name: material
  palette:
    - scheme: default
      primary: blue grey
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil

nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: QUICKSTART.md
    - Linux Installation: INSTALL_LINUX.md
    - Docker Installation: INSTALL_DOCKER.md
  - Guides:
    - Uninstall Guide: UNINSTALL.md
    - Security Best Practices: SECURITY.md
    - Release Process: RELEASE_PROCESS.md
  - Support:
    - FAQ: FAQ.md
    - Troubleshooting: TROUBLESHOOTING.md

plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  - mermaid2:
      arguments:
        theme: auto

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - tables

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GLINCKER/glinrdock-release
      name: GitHub Repository
    - icon: fontawesome/solid/globe
      link: https://glincker.com
      name: GLINCKER LLC
  version:
    provider: mike

copyright: Copyright &copy; 2025 GLINCKER LLC. All rights reserved.