name: Bug Report
description: Report a bug or issue with GlinrDock
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the sections below to help us understand and reproduce the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-flight checklist
      description: Please verify you've completed these steps
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I have read the troubleshooting guide
          required: true
        - label: I am using the latest version of GlinrDock
          required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Clear steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: input
    id: controller_version
    attributes:
      label: Controller Version
      description: What version of GlinrDock Controller are you running?
      placeholder: v1.0.0
    validations:
      required: true

  - type: textarea
    id: version_output
    attributes:
      label: Version Command Output
      description: |
        Please run `glinrdockd --version` and paste the complete output below.
        If using Docker Compose, run: `docker compose exec glinrdock glinrdockd --version`
      placeholder: |
        glinrdockd version v1.0.0
        Build: abc123def
        Built: 2025-01-01T12:00:00Z
        Go: go1.21.0
      render: shell
    validations:
      required: true

  - type: dropdown
    id: installation
    attributes:
      label: Installation Method
      description: How did you install GlinrDock?
      options:
        - systemd service (install script)
        - Docker Compose
        - Manual binary installation
        - Container (docker run)
        - Other (specify in additional context)
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System and Version
      description: What operating system and version are you using?
      placeholder: "Ubuntu 22.04.3 LTS, CentOS Stream 8, macOS 13.6, etc."
    validations:
      required: true

  - type: input
    id: docker
    attributes:
      label: Docker Version
      description: What version of Docker are you using? (Run `docker --version`)
      placeholder: "Docker version 24.0.7, build afdd53b"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Log Output (Required)
      description: |
        Please provide relevant log output from the time the issue occurred:
        
        **For systemd installations:**
        ```bash
        sudo journalctl -u glinrdockd.service --no-pager -l --since="10 minutes ago"
        ```
        
        **For Docker Compose:**
        ```bash
        docker compose logs --tail=50 glinrdock
        ```
        
        **For docker run:**
        ```bash
        docker logs --tail=50 glinrdock
        ```
      placeholder: Paste log output here (last 50 lines or relevant error messages)...
      render: shell
    validations:
      required: true

  - type: textarea
    id: health_check
    attributes:
      label: Health Endpoint Output
      description: |
        Please check the health endpoint status by running:
        ```bash
        curl -s http://localhost:8080/v1/health | jq .
        ```
        Or without jq:
        ```bash
        curl -s http://localhost:8080/v1/health
        ```
        If the endpoint is not responding, note that in the output.
      placeholder: |
        {
          "status": "healthy",
          "timestamp": "2025-01-01T12:00:00Z",
          "version": "v1.0.0"
        }
        
        OR: "Connection refused" / "Timeout" / other error message
      render: json
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: |
        Please share your configuration (remove sensitive information like tokens):
        - Environment variables
        - Docker Compose configuration
        - Any custom settings
      placeholder: Paste configuration here...
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem:
        - Screenshots
        - Error messages
        - Network configuration
        - Browser information (for UI issues)
      placeholder: Any additional information...

  - type: dropdown
    id: priority
    attributes:
      label: Priority/Severity
      description: How severe is this issue?
      options:
        - Low (minor inconvenience)
        - Medium (affects functionality but workaround exists)
        - High (major functionality broken)
        - Critical (system unusable, security issue)
    validations:
      required: true