name: Bug Report
description: Report a bug or issue with GlinrDock
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the sections below to help us understand and reproduce the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-flight checklist
      description: Please verify you've completed these steps
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I have read the troubleshooting guide
          required: true
        - label: I am using the latest version of GlinrDock
          required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Clear steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: GlinrDock Version
      description: What version of GlinrDock are you running?
      placeholder: v1.0.0
    validations:
      required: true

  - type: dropdown
    id: installation
    attributes:
      label: Installation Method
      description: How did you install GlinrDock?
      options:
        - Install script (recommended)
        - Docker Compose
        - Manual installation
        - Other (specify in additional context)
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: Ubuntu 22.04, CentOS 8, etc.
    validations:
      required: true

  - type: input
    id: docker
    attributes:
      label: Docker Version
      description: What version of Docker are you using?
      placeholder: Docker version 20.10.21
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Log Output
      description: |
        Please provide relevant log output. For systemd installations use:
        `sudo journalctl -u glinrdock.service --no-pager -l`
        
        For Docker Compose use:
        `docker-compose logs glinrdock`
      placeholder: Paste log output here...
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: |
        Please share your configuration (remove sensitive information like tokens):
        - Environment variables
        - Docker Compose configuration
        - Any custom settings
      placeholder: Paste configuration here...
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem:
        - Screenshots
        - Error messages
        - Network configuration
        - Browser information (for UI issues)
      placeholder: Any additional information...

  - type: dropdown
    id: priority
    attributes:
      label: Priority/Severity
      description: How severe is this issue?
      options:
        - Low (minor inconvenience)
        - Medium (affects functionality but workaround exists)
        - High (major functionality broken)
        - Critical (system unusable, security issue)
    validations:
      required: true