blank_issues_enabled: false
contact_links:
  - name: 🔒 Security Vulnerability Report
    url: https://github.com/GLINCKER/glinrdock-release/blob/main/docs/SECURITY.md
    about: Report security vulnerabilities privately through our coordinated disclosure process
  - name: 📖 Documentation & Installation Help
    url: https://glincker.github.io/glinrdock-release/
    about: Visit our documentation site for installation guides and troubleshooting
  - name: 💬 General Discussion
    url: https://github.com/GLINCKER/glinrdock-release/discussions
    about: Ask questions and discuss features with the community
  - name: 📞 Commercial Support
    url: mailto:support@glincker.com
    about: Contact GLINCKER LLC for enterprise support and licensing