name: Feature Request
description: Suggest a new feature or enhancement for GlinrDock
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please provide detailed information about your request.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-flight checklist
      description: Please verify you've completed these steps
      options:
        - label: I have searched existing issues and this feature hasn't been requested
          required: true
        - label: I have checked the roadmap for planned features
          required: true
        - label: This is a single, well-defined feature request
          required: true

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief, clear summary of the feature you'd like to see
      placeholder: Summarize the feature request in 1-2 sentences...
    validations:
      required: true

  - type: textarea
    id: business_outcome
    attributes:
      label: Business Outcome & Impact
      description: |
        What business problem does this solve? What value would it provide?
        Focus on the "why" and business impact, not the "how".
      placeholder: |
        Example business outcomes:
        - "Reduce deployment time from 30 minutes to 5 minutes"
        - "Enable team to manage 50+ containers without manual oversight"
        - "Eliminate security compliance violations during container deployment"
        - "Save 10 hours per week on container monitoring tasks"
      
        Describe the impact:
        - Who benefits from this feature?
        - How does it improve their workflow?
        - What are the measurable benefits?
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Current Problem/Gap
      description: |
        What specific problem or limitation currently prevents achieving the business outcome?
        Be specific about what doesn't work today.
      placeholder: |
        Current state description:
        - "Currently we have to manually..." 
        - "There's no way to..."
        - "Users get frustrated because..."
        - "We lose time/money because..."
    validations:
      required: true

  - type: textarea
    id: minimal_solution
    attributes:
      label: Minimal Viable Change
      description: |
        What is the smallest possible change that would deliver meaningful value?
        Think MVP - what's the 80/20 solution that provides the most impact with least complexity?
      placeholder: |
        Minimal solution that would help:
        - "Just need a simple button to..."
        - "A basic API endpoint that returns..."
        - "A config option to enable/disable..."
        - "Show status in the UI so users can..."
        
        This doesn't need to be the full solution, just the minimum that provides value.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        Describe alternatives you've considered:
        - Other ways to solve this problem
        - Existing workarounds
        - Why the proposed solution is better
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - API Enhancement
        - UI/UX Improvement
        - Security Feature
        - Performance Optimization
        - Integration/Plugin
        - Monitoring/Observability
        - Container Management
        - Project Management
        - Documentation
        - Other (specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: business_priority
    attributes:
      label: Business Priority
      description: What's the business impact if this feature is not implemented?
      options:
        - Low (nice to have, minor convenience improvement)
        - Medium (noticeable productivity/efficiency gain)
        - High (significant workflow blocker or competitive advantage)
        - Critical (major business process blocked or security/compliance issue)
    validations:
      required: true

  - type: input
    id: timeline
    attributes:
      label: Business Timeline
      description: Is there a business deadline or timeline driving this request?
      placeholder: "Q2 2025 product launch, upcoming audit, team scaling to 50+ developers, etc."
    validations:
      required: false

  - type: dropdown
    id: user_impact
    attributes:
      label: User Impact Scope
      description: How many users or teams would benefit from this feature?
      options:
        - Individual (just me or my specific use case)
        - Team (5-15 people on my team)
        - Department (multiple teams, 15-50 people)  
        - Organization (company-wide, 50+ people)
        - Community (many external users would benefit)
    validations:
      required: true

  - type: textarea
    id: use_cases
    attributes:
      label: Use Cases
      description: Provide specific use cases or scenarios where this feature would be beneficial
      placeholder: |
        Example use cases:
        1. As a DevOps engineer, I want to... so that...
        2. When managing multiple projects, I need to... because...
        3. During deployment, it would be helpful to... to avoid...
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: |
        If applicable, provide mockups, wireframes, or examples:
        - UI mockups or sketches
        - API endpoint examples
        - Configuration examples
        - Screenshots from other tools
      placeholder: |
        You can attach images by dragging and dropping them here.
        For API examples, use code blocks:
        ```json
        {
          "example": "api_response"
        }
        ```

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        Any other information that would be helpful:
        - Links to similar features in other tools
        - Technical constraints to consider
        - Compatibility requirements
        - Performance considerations
      placeholder: Any additional information...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you interested in contributing to this feature?
      options:
        - label: I would be willing to contribute to implementing this feature
          required: false
        - label: I would be available to help test this feature
          required: false
        - label: I would be willing to help with documentation
          required: false